--ADVANCED BUSINESS ANALYSIS
/*
INSIGHTS:
RECOMMENDATION:
*/
--------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------
--1.Customer lifetime value
--------------------------------------------------------------------------------------------
/*
OBJECTIVE:To identify the lifetime value of the customer
*/ 
SELECT top 10
    customerID,
    tenure,
    MonthlyCharges,
    ROUND(tenure * MonthlyCharges,2) AS Customer_Lifetime_Value
FROM customer_churn
ORDER BY Customer_Lifetime_Value DESC;

/*
INSIGHTS:Customers with long tenure and high monthly plans generate the highest revenue.
         Losing these customers would have a significant financial impact.
RECOMMENDATION:Create VIP retention programs.
               Offer loyalty discounts after 2–3 years.
               Assign dedicated customer support for high-value customers.
*/
---------------------------------------------------------------------------------------------------------
--2.Rank customers by revenue
/*OBJECTIVE:It ranks the based on their revenue
*/
select
customerid,
monthlycharges,
tenure,
round(monthlycharges*tenure,2) as revenue,
rank() over(order by monthlycharges desc) as revenue_rank
from Customer_Churn

/*
INSIGHTS:Ranks customers from highest to lowest revenue.
RECOMMENDATION:Top-ranked customers should receive
               Premium support
               Exclusive offers
               Loyalty rewards
*/
---------------------------------------------------------------------------------------------------
--3.Revenue by customer segment
/*
OBJECTIVE:It divides the customers into 3 segments based on their revenue
*/
SELECT
CASE
WHEN MonthlyCharges>=80 THEN 'High Value'
WHEN MonthlyCharges BETWEEN 50 AND 79.99 THEN 'Medium Value'
ELSE 'Low Value'
END AS CustomerSegment,
COUNT(*) AS Customers,
ROUND(SUM(MonthlyCharges),2) AS MonthlyRevenue
FROM customer_churn
GROUP BY 
CASE
WHEN MonthlyCharges>=80 THEN 'High Value'
WHEN MonthlyCharges BETWEEN 50 AND 79.99 THEN 'Medium Value'
ELSE 'Low Value'
END
ORDER BY MonthlyRevenue DESC;

/*
INSIGHTS:Shows which customer segment contributes the highest monthly revenue.
RECOMMENDATION:Invest more in retaining High Value customers.
*/
--------------------------------------------------------------------------------------------
--4.Prercentile analysis
/*
OBJECTIVE:It divides and identifies the customers as different groups based on their expenses
*/
SELECT
customerID,
MonthlyCharges,
NTILE(4) OVER(
ORDER BY MonthlyCharges DESC
) AS RevenueQuartile
FROM customer_churn;

/*
INSIGHTS:Divides customers into four spending groups.
RECOMMENDATION:Target premium offers to the top 25% spending customers.
*/
--------------------------------------------------------------------------------------------
--5.Running revenue
/*
OBJECTIVE:
*/
Select
customerid,
monthlycharges,
sum(monthlycharges) over(order by monthlycharges desc) as running_revenue
from customer_churn

/*
INSIGHTS:Demonstrates cumulative revenue generated by customers.
RECOMMENDATION:Useful for identifying how much revenue comes from top-paying customers.
*/
--------------------------------------------------------------------------------------------
--6.Churn prediction
/*OBJECTIVE:It divides the customers into different categories giving them risk scores inorder to predict the churn
            and to prevent high churn rate.
*/
SELECT
customerID,
CASE
WHEN Contract='Month-to-month' THEN 3 
WHEN TechSupport='0' THEN 2 
WHEN OnlineSecurity='0' THEN 2 
WHEN tenure<12 THEN 3 ELSE 0 END
AS RiskScore
FROM customer_churn
ORDER BY RiskScore DESC;

/*
INSIGHTS:Creates a simple churn risk score based on multiple factors.
RECOMMENDATION:Customers with higher scores should receive 
               proactive retention calls, service upgrades, or personalized offers.
*/
--------------------------------------------------------------------------------------------
--7.Which contract type has the highest churn rate
/*
OBJECTIVE:Analyze customer churn across different contract types to identify
          which contracts are most vulnerable to customer loss.
*/
WITH Contract_Churn AS
(
    SELECT
        Contract,
        COUNT(*) AS Total_Customers,
        SUM(CASE WHEN Churn = 1 THEN 1 ELSE 0 END) AS Churned_Customers
    FROM dbo.Customer_Churn
    GROUP BY Contract
)

SELECT
    Contract,
    Total_Customers,
    Churned_Customers,
    ROUND(Churned_Customers * 100.0 / Total_Customers, 2) AS Churn_Rate
FROM Contract_Churn
ORDER BY Churn_Rate DESC;

/* 
INSIGHTS:-Month-to-month customers have an extremely high churn rate (42.71%).
         -Customers on two-year contracts are the most loyal.
RECOMMENDATIONS:Offer discounts or incentives to encourage month-to-month customers 
                to switch to one-year or two-year contracts.
*/
--------------------------------------------------------------------------------------------
--8.who are the highest paying customers
/*
OBJECTIVE:It lists the highest paying customers from highest to lowest based on the number
*/
select
customerid,
monthlycharges,
totalcharges,
row_number() over(order by monthlycharges desc) customer_num
from customer_churn

/* 
INSIGHTS:-These customers contribute significantly to monthly recurring revenue.
RECOMMENDATIONS:Provide premium customer support and loyalty benefits to retain 
                high-value customers.
*/
--------------------------------------------------------------------------------------------
--9.How can customers be ranked on monthly charges

--RANK()
/*
OBJECTIVE:It ranks the customers based on their monthly charges leaving gaps when ties
*/
select
customerid,
monthlycharges,
rank() over(order by monthlycharges desc) as customer_rank
from customer_churn

/* 
INSIGHTS:Useful for identifying the top-paying customers while properly handling ties.
RECOMMENDATIONS:Use rankings to identify VIP customers for targeted marketing campaigns
*/

--DENSERANK()
--RANK()
/*
OBJECTIVE:It ranks the customers based on their monthly charges Without leaving gaps/skipping rank numbers
          in case of gaps.
*/
select
customerid,
monthlycharges,
dense_rank() over(order by monthlycharges desc) as customer_rank
from customer_churn

/* 
INSIGHTS:Provides a compact ranking that is useful for reporting and customer segmentation.
RECOMMENDATIONS:Use dense ranking when grouping customers into premium tiers.
*/
--------------------------------------------------------------------------------------------
--10.which customers pay more than the average monthly charge
/*
OBJECTIVE:Returns customers whose monthly charges are above the overall average.
*/
select
customerid,
monthlycharges
from customer_churn
where monthlycharges>
(select
avg(monthlycharges) from customer_churn)

/*
INSIGHTS:These customers contribute above-average revenue
         and should be considered high-value accounts.
RECOMMENDATIONS:Prioritize these customers for loyalty programs 
                and premium service offerings.
*/
--------------------------------------------------------------------------------------------------------
--11.View of high risk customeres
/*
OBJECTIVE:Creates a reusable view containing churned month-to-month customers.
*/
CREATE VIEW  High_Risk_Customers  AS

SELECT
    customerID,
    Contract,
    tenure,
    MonthlyCharges
FROM Customer_Churn
WHERE Churn=1
AND Contract='Month-to-month';
--to verify the view is created:
SELECT * from high_risk_customers

/*
INSIGHTS:This view enables analysts to quickly access the highest-risk customer
         segment without rewriting the query.
RECOMMENDATIONS:Use this view for recurring retention analysis and reporting.
*/
--------------------------------------------------------------------------------------------------------



